# Generated by Django 5.1.3 on 2024-11-21 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место выполнения привычки",
                        max_length=500,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        help_text="Введите время выполнения привычки",
                        max_length=500,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие привычки",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        help_text="укажите является ли привычка приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("1", "Каждый день"),
                            ("2", "Через день"),
                            ("3", "Через два дня"),
                            ("4", "Через три дня"),
                            ("5", "Через четыре дня"),
                            ("6", "Через пять дней"),
                            ("7", "Раз в неделю"),
                        ],
                        help_text="Выберете периодичность",
                        max_length=10,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "lead_time",
                    models.PositiveSmallIntegerField(
                        help_text="Укажите примерное время выполнения в секундах",
                        verbose_name="Примерное время выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        help_text="Укажите статус публичности",
                        verbose_name="Статус публичности",
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
