# Generated by Django 5.1.3 on 2024-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="next_send_date",
            field=models.DateTimeField(
                verbose_name="Дата следующей отправки напоминания"
            ),
        ),
    ]
