# Generated by Django 5.1.3 on 2024-11-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_habits", "0002_alter_habit_next_send_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="next_send_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата следующей отправки напоминания",
            ),
        ),
    ]
