# Generated by Django 5.1.3 on 2024-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_habits", "0002_alter_habit_options_habit_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время обновления"
            ),
        ),
    ]
