# Generated by Django 5.1.3 on 2024-11-25 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_habits", "0004_habit_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="укажите является ли привычка приятной",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Укажите статус публичности",
                verbose_name="Статус публичности",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="lead_time",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите примерное время выполнения в секундах",
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="Примерное время выполнения",
            ),
        ),
    ]
